const PDFDocument = require("pdfkit");
const Medicine = require("../models/Medicine");
const AuditLog = require("../models/AuditLog");
const HealthCenter = require("../models/HealthCenter");
const DispensingHistory = require("../models/DispensingHistory");
const { createAuditLog } = require("../utils/auditLogger");

const hasCentralReadAccess = (role) => role === "cho_admin" || role === "cho_monitor";

exports.generateInventoryReport = async (req, res) => {
  try {
    const query = { isActive: true };

    if (hasCentralReadAccess(req.user.role) && req.query.healthCenter) {
      query.healthCenter = req.query.healthCenter;
    } else if (!hasCentralReadAccess(req.user.role)) {
      query.healthCenter = req.user.healthCenter._id;
    }

    const medicines = await Medicine.find(query)
      .populate("healthCenter", "name barangay city")
      .populate("addedBy", "firstName lastName")
      .sort({ name: 1 });

    const healthCenter = hasCentralReadAccess(req.user.role) && req.query.healthCenter
      ? await HealthCenter.findById(req.query.healthCenter)
      : req.user.healthCenter;

    const doc = new PDFDocument({ margin: 40, size: "A4", layout: "landscape" });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=inventory-report-${new Date().toISOString().split("T")[0]}.pdf`
    );

    doc.pipe(res);

    // Header
    doc
      .fontSize(18)
      .font("Helvetica-Bold")
      .text("MEDICINE INVENTORY REPORT", { align: "center" });
    doc.moveDown(0.3);
    doc
      .fontSize(12)
      .font("Helvetica")
      .text(
        healthCenter
          ? `${healthCenter.name} - Barangay ${healthCenter.barangay}`
          : "All Health Centers (City Health Office)",
        { align: "center" }
      );
    doc
      .fontSize(10)
      .text(`Generated on: ${new Date().toLocaleDateString("en-PH", { dateStyle: "long" })}`, {
        align: "center",
      });
    doc
      .text(`Generated by: ${req.user.firstName} ${req.user.lastName}`, {
        align: "center",
      });
    doc.moveDown(1);

    // Summary
    const now = new Date();
    const threeMonths = new Date();
    threeMonths.setMonth(threeMonths.getMonth() + 3);

    const totalItems = medicines.length;
    const totalQty = medicines.reduce((sum, m) => sum + m.quantity, 0);
    const lowStock = medicines.filter((m) => m.quantity > 0 && m.quantity <= m.minimumStock).length;
    const outOfStock = medicines.filter((m) => m.quantity === 0).length;
    const expired = medicines.filter((m) => m.expiryDate < now).length;
    const expiringSoon = medicines.filter(
      (m) => m.expiryDate >= now && m.expiryDate <= threeMonths
    ).length;

    doc.fontSize(11).font("Helvetica-Bold").text("SUMMARY");
    doc.moveDown(0.3);
    doc
      .fontSize(9)
      .font("Helvetica")
      .text(
        `Total Items: ${totalItems}  |  Total Quantity: ${totalQty}  |  Low Stock: ${lowStock}  |  Out of Stock: ${outOfStock}  |  Expired: ${expired}  |  Expiring Soon: ${expiringSoon}`
      );
    doc.moveDown(0.8);

    // Table header
    const tableTop = doc.y;
    const colWidths = [140, 80, 70, 60, 50, 60, 80, 70, 80];
    const colHeaders = [
      "Medicine Name",
      "Category",
      "Dosage",
      "Form",
      "Qty",
      "Unit",
      "Expiry Date",
      "Batch #",
      "Status",
    ];

    doc.fontSize(8).font("Helvetica-Bold");
    let x = 40;
    colHeaders.forEach((header, i) => {
      doc.text(header, x, tableTop, { width: colWidths[i], align: "left" });
      x += colWidths[i];
    });

    doc
      .moveTo(40, tableTop + 14)
      .lineTo(40 + colWidths.reduce((a, b) => a + b, 0), tableTop + 14)
      .stroke();

    // Table rows
    let y = tableTop + 20;
    doc.font("Helvetica").fontSize(7);

    medicines.forEach((med) => {
      if (y > 540) {
        doc.addPage();
        y = 40;
        doc.fontSize(8).font("Helvetica-Bold");
        let hx = 40;
        colHeaders.forEach((header, i) => {
          doc.text(header, hx, y, { width: colWidths[i], align: "left" });
          hx += colWidths[i];
        });
        doc
          .moveTo(40, y + 14)
          .lineTo(40 + colWidths.reduce((a, b) => a + b, 0), y + 14)
          .stroke();
        y += 20;
        doc.font("Helvetica").fontSize(7);
      }

      let status = "In Stock";
      if (med.quantity === 0) status = "OUT OF STOCK";
      else if (med.quantity <= med.minimumStock) status = "LOW STOCK";
      if (med.expiryDate < now) status = "EXPIRED";
      else if (med.expiryDate <= threeMonths) status += " / EXPIRING";

      const row = [
        med.name,
        med.category,
        med.dosageStrength,
        med.dosageForm,
        med.quantity.toString(),
        med.unit,
        med.expiryDate.toLocaleDateString("en-PH"),
        med.batchNumber || "-",
        status,
      ];

      x = 40;
      row.forEach((cell, i) => {
        doc.text(cell, x, y, { width: colWidths[i], align: "left" });
        x += colWidths[i];
      });

      y += 14;
    });

    // Footer
    doc.moveDown(2);
    doc
      .fontSize(8)
      .font("Helvetica")
      .text(
        "This report is system-generated. For official use of the Barangay Health Center and City Health Office.",
        40,
        y + 20,
        { align: "center" }
      );

    doc.end();

    await createAuditLog({
      action: "REPORT_GENERATED",
      description: "Generated inventory PDF report",
      user: req.user._id,
      healthCenter: req.user.healthCenter._id,
      ipAddress: req.ip,
    });
  } catch (error) {
    if (process.env.NODE_ENV !== "production") {
      console.error("Generate report error:", error);
    }
    res.status(500).json({ message: "Failed to generate report" });
  }
};

exports.getAuditLogs = async (req, res) => {
  try {
    const { page = 1, limit = 50, action, startDate, endDate } = req.query;

    const query = {};

    if (!hasCentralReadAccess(req.user.role)) {
      query.healthCenter = req.user.healthCenter._id;
    } else if (req.query.healthCenter) {
      query.healthCenter = req.query.healthCenter;
    }

    if (action) query.action = action;

    if (startDate || endDate) {
      query.createdAt = {};
      if (startDate) query.createdAt.$gte = new Date(startDate);
      if (endDate) query.createdAt.$lte = new Date(endDate);
    }

    const skip = (parseInt(page) - 1) * parseInt(limit);

    const [logs, total] = await Promise.all([
      AuditLog.find(query)
        .populate("user", "firstName lastName email")
        .populate("medicine", "name dosageStrength")
        .populate("healthCenter", "name barangay")
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(parseInt(limit)),
      AuditLog.countDocuments(query),
    ]);

    res.json({
      logs,
      pagination: {
        current: parseInt(page),
        pages: Math.ceil(total / parseInt(limit)),
        total,
        limit: parseInt(limit),
      },
    });
  } catch (error) {
    if (process.env.NODE_ENV !== "production") {
      console.error("Get audit logs error:", error);
    }
    res.status(500).json({ message: "Failed to retrieve audit logs" });
  }
};

exports.getDispensingHistory = async (req, res) => {
  try {
    const { page = 1, limit = 25, medicine, startDate, endDate } = req.query;

    const query = {};
    if (!hasCentralReadAccess(req.user.role)) {
      query.healthCenter = req.user.healthCenter._id;
    } else if (req.query.healthCenter) {
      query.healthCenter = req.query.healthCenter;
    }

    if (medicine) query.medicine = medicine;
    if (startDate || endDate) {
      query.createdAt = {};
      if (startDate) query.createdAt.$gte = new Date(startDate);
      if (endDate) query.createdAt.$lte = new Date(endDate);
    }

    const skip = (parseInt(page) - 1) * parseInt(limit);

    const [records, total] = await Promise.all([
      DispensingHistory.find(query)
        .populate("medicine", "name dosageStrength unit category qrCode")
        .populate("healthCenter", "name barangay")
        .populate("dispensedBy", "firstName lastName role")
        .sort({ createdAt: -1 })
        .skip(skip)
        .limit(parseInt(limit)),
      DispensingHistory.countDocuments(query),
    ]);

    res.json({
      records,
      pagination: {
        current: parseInt(page),
        pages: Math.ceil(total / parseInt(limit)),
        total,
        limit: parseInt(limit),
      },
    });
  } catch (error) {
    if (process.env.NODE_ENV !== "production") {
      console.error("Get dispensing history error:", error);
    }
    res.status(500).json({ message: "Failed to retrieve dispensing history" });
  }
};

exports.getForecast60Day = async (req, res) => {
  try {
    const horizonDays = 60;
    const now = new Date();
    const fromDate = new Date(now);
    fromDate.setDate(fromDate.getDate() - horizonDays);

    const medicineQuery = { isActive: true };
    if (!hasCentralReadAccess(req.user.role)) {
      medicineQuery.healthCenter = req.user.healthCenter._id;
    } else if (req.query.healthCenter) {
      medicineQuery.healthCenter = req.query.healthCenter;
    }

    const medicines = await Medicine.find(medicineQuery)
      .select("name category quantity minimumStock unit healthCenter")
      .populate("healthCenter", "name barangay");

    const medicineIds = medicines.map((m) => m._id);
    const usageAgg = await DispensingHistory.aggregate([
      {
        $match: {
          medicine: { $in: medicineIds },
          createdAt: { $gte: fromDate },
        },
      },
      {
        $group: {
          _id: "$medicine",
          totalDispensed: { $sum: "$quantity" },
          txCount: { $sum: 1 },
          lastDispensedAt: { $max: "$createdAt" },
        },
      },
    ]);

    const usageMap = new Map(usageAgg.map((row) => [String(row._id), row]));

    const forecasts = medicines.map((med) => {
      const usage = usageMap.get(String(med._id));
      const totalDispensed = usage?.totalDispensed || 0;
      const movingAveragePerDay = Number((totalDispensed / horizonDays).toFixed(2));
      const daysUntilStockout = movingAveragePerDay > 0
        ? Number((med.quantity / movingAveragePerDay).toFixed(1))
        : null;

      return {
        medicineId: med._id,
        medicineName: med.name,
        category: med.category,
        healthCenter: med.healthCenter,
        currentQuantity: med.quantity,
        minimumStock: med.minimumStock,
        unit: med.unit,
        movingAverage60Day: movingAveragePerDay,
        totalDispensed60Day: totalDispensed,
        transactions60Day: usage?.txCount || 0,
        lastDispensedAt: usage?.lastDispensedAt || null,
        projectedDaysUntilStockout: daysUntilStockout,
      };
    });

    forecasts.sort((a, b) => {
      if (a.projectedDaysUntilStockout == null) return 1;
      if (b.projectedDaysUntilStockout == null) return -1;
      return a.projectedDaysUntilStockout - b.projectedDaysUntilStockout;
    });

    res.json({
      horizonDays,
      forecasts,
      generatedAt: new Date().toISOString(),
    });
  } catch (error) {
    if (process.env.NODE_ENV !== "production") {
      console.error("Get forecast error:", error);
    }
    res.status(500).json({ message: "Failed to retrieve forecast" });
  }
};

exports.generateLogsReport = async (req, res) => {
  try {
    const { action, startDate, endDate } = req.query;
    const query = {};

    if (!hasCentralReadAccess(req.user.role)) {
      query.healthCenter = req.user.healthCenter._id;
    } else if (req.query.healthCenter) {
      query.healthCenter = req.query.healthCenter;
    }

    if (action) query.action = action;
    if (startDate || endDate) {
      query.createdAt = {};
      if (startDate) query.createdAt.$gte = new Date(startDate);
      if (endDate) query.createdAt.$lte = new Date(endDate);
    }

    const dispensingQuery = { ...query };
    delete dispensingQuery.action;

    const [auditLogs, dispensingRecords] = await Promise.all([
      AuditLog.find(query)
        .populate("user", "firstName lastName")
        .populate("healthCenter", "name barangay")
        .sort({ createdAt: -1 })
        .limit(500),
      DispensingHistory.find(dispensingQuery)
        .populate("medicine", "name category unit")
        .populate("dispensedBy", "firstName lastName")
        .populate("healthCenter", "name barangay")
        .sort({ createdAt: -1 })
        .limit(500),
    ]);

    const doc = new PDFDocument({ margin: 40, size: "A4", layout: "landscape" });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename=logs-report-${new Date().toISOString().split("T")[0]}.pdf`
    );

    doc.pipe(res);

    doc.font("Helvetica-Bold").fontSize(16).text("COMPLIANCE LOGS REPORT", { align: "center" });
    doc.moveDown(0.3);
    doc.font("Helvetica").fontSize(9).text(`Generated: ${new Date().toLocaleString("en-PH")}`, { align: "center" });
    doc.text(`Prepared by: ${req.user.firstName} ${req.user.lastName}`, { align: "center" });
    doc.moveDown(1);

    doc.font("Helvetica-Bold").fontSize(11).text("Section A: Audit Trail");
    doc.moveDown(0.3);

    const auditHeaders = ["Date/Time", "Action", "Description", "User", "Center"];
    const auditWidths = [120, 120, 280, 110, 140];

    let x = 40;
    let y = doc.y;
    doc.font("Helvetica-Bold").fontSize(8);
    auditHeaders.forEach((header, i) => {
      doc.text(header, x, y, { width: auditWidths[i] });
      x += auditWidths[i];
    });
    y += 14;
    doc.moveTo(40, y).lineTo(40 + auditWidths.reduce((a, b) => a + b, 0), y).stroke();
    y += 4;

    doc.font("Helvetica").fontSize(7);
    for (const log of auditLogs) {
      if (y > 520) {
        doc.addPage();
        y = 40;
      }
      const row = [
        new Date(log.createdAt).toLocaleString("en-PH"),
        log.action,
        log.description,
        log.user ? `${log.user.firstName} ${log.user.lastName}` : "System",
        log.healthCenter?.name || "-",
      ];
      x = 40;
      row.forEach((cell, i) => {
        doc.text(String(cell), x, y, { width: auditWidths[i], ellipsis: true });
        x += auditWidths[i];
      });
      y += 13;
    }

    if (y > 470) {
      doc.addPage();
      y = 40;
    } else {
      y += 20;
    }

    doc.font("Helvetica-Bold").fontSize(11).text("Section B: QR Dispensing Records", 40, y);
    y += 18;

    const dispHeaders = ["Date/Time", "Medicine", "Program", "Qty", "Staff", "Center"];
    const dispWidths = [120, 220, 140, 70, 120, 140];
    x = 40;
    doc.font("Helvetica-Bold").fontSize(8);
    dispHeaders.forEach((header, i) => {
      doc.text(header, x, y, { width: dispWidths[i] });
      x += dispWidths[i];
    });
    y += 14;
    doc.moveTo(40, y).lineTo(40 + dispWidths.reduce((a, b) => a + b, 0), y).stroke();
    y += 4;

    doc.font("Helvetica").fontSize(7);
    for (const rec of dispensingRecords) {
      if (y > 520) {
        doc.addPage();
        y = 40;
      }
      const row = [
        new Date(rec.createdAt).toLocaleString("en-PH"),
        rec.medicine?.name || "Unknown",
        rec.medicine?.category || "-",
        `${rec.quantity} ${rec.medicine?.unit || "pcs"}`,
        rec.dispensedBy ? `${rec.dispensedBy.firstName} ${rec.dispensedBy.lastName}` : "-",
        rec.healthCenter?.name || "-",
      ];
      x = 40;
      row.forEach((cell, i) => {
        doc.text(String(cell), x, y, { width: dispWidths[i], ellipsis: true });
        x += dispWidths[i];
      });
      y += 13;
    }

    doc.end();

    await createAuditLog({
      action: "REPORT_GENERATED",
      description: "Generated compliance logs PDF report",
      user: req.user._id,
      healthCenter: req.user.healthCenter._id,
      ipAddress: req.ip,
    });
  } catch (error) {
    if (process.env.NODE_ENV !== "production") {
      console.error("Generate logs report error:", error);
    }
    res.status(500).json({ message: "Failed to generate logs report" });
  }
};
